### ISSUE TITLE
Yielding the hdrhistogram crate name

### ISSUE THREAD

**Issue by jonhoo** [jsgf/rust-hdrhistogram#1]
I'm the maintainer of the [hdrsample crate](https://crates.io/crates/hdrsample), a pure-Rust implementation of HdrHistogram. It's pretty close to feature complete now, and Gil Tene (@giltene; the original HdrHistogram author) wants to move it into the official HdrHistogram GitHub organization (jonhoo/hdrsample#60).

When doing so, we'd also like to rename the crate to hdrhistogram to maintain consistency with the various other HdrHistogram implementations. However, that name is already taken by this crate. Given that it seems to no longer be maintained, we've been wondering whether we could convince you to give up the hdrhistogram crate name so we could replace it with the now-official Rust crate?

If you decide that's okay, you unfortunately can't currently delete or rename crates on crates.io (rust-lang/crates.io#166), but we should be able to just replace the crate in-place with the Rust version if you add me using `cargo owner`: http://doc.crates.io/crates-io.html#cargo-owner

Let me know what you think!
Cheers,
Jon

**Comment by jsgf** [comment]
Hi - I have no problem w this in principle. Let me look at the details.

**Comment by jsgf** [comment]
OK, so it looks like this hdrhistogram has a non-zero number of users, so it should still be available. I think we rename the crate to hdrhistogram_c in crates.io and put a note in the README for the Rust hdrhistogram so they can easily update their Cargo.toml.

**Comment by jonhoo** [comment]
Huh interesting... Those may just be bot downloads. But yes, we should be on the safe side, so that seems like a reasonable course of action! The way to go about it would then likely be:

1. You upload your crate to crates.io as hdrhistogram_c
2. I push a change to my crate's README to point people to hdrhistogram_c
3. You give me owner access to crates.io/hdrhistogram
4. I publish the current version of my crate to crates.io/hdrhistogram (should work fine as mine has a higher version number than yours)
5. I push a new minor version of `hdrsample` where the main types are all deprecated, and where the docs say to use `hdrhistogram` instead.

How does that sound?

/cc @marshallpierce

**Comment by jonhoo** [comment]
@jsgf ping just to keep this on your radar.

**Comment by jonhoo** [comment]
@jsgf still okay with going ahead with this?

**Comment by jsgf** [comment]
I'm doing the update at the moment. I guess you won't be able to recycle any of the old version numbers, so if you start at >=0.2 then existing users with Cargo.lock files will build unmodified, but new users will need to switch to hdrhistogram_c to continue using the API; otherwise they can convert to the hdrhistogram API.

**Comment by jonhoo** [comment]
Yup, the intention was to continue `hdrsample`'s versioning, which is currently at `6.0.1`. I'll start the migration from my end, including adding a link to [`hdrhistogram_c`](https://crates.io/crates/hdrhistogram_c). Thanks!
